name: juweier_music
version: 3.5.10+3510
description: 橘味儿音乐 Android/iOS 三端联调测试客户端
publish_to: 'none'
environment:
  sdk: '>=3.10.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  just_audio: ^0.10.5
  path_provider: ^2.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
flutter:
  uses-material-design: true
  assets:
    - assets/juweier_icon.png
    - assets/juweier_brand_mark_v322.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/juweier_icon.png
  min_sdk_android: 23
  remove_alpha_ios: true
